# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success~=^main
    actions:
      merge:
        method: squash

pull_request_rules:
  - name: Be Bira's friend
    conditions:
      - author~=ubiratansoares
      - check-success~=^main
    actions:
      merge:
        method: squash
