# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Renovate pull requests
    conditions:
      - author~=^renovate\[bot\]$
      - check-success=main (ubuntu-22.04, 3.9.16)
      - check-success=main (ubuntu-22.04, 3.10.11)
      - check-success=main (macos-12, 3.9.16)
      - check-success=main (macos-12, 3.10.11)
    actions:
      merge:
        method: squash

  - name: Be owner's friend
    conditions:
      - author~=ubiratansoares
      - check-success=main (ubuntu-22.04, 3.9.16)
      - check-success=main (ubuntu-22.04, 3.10.11)
      - check-success=main (macos-12, 3.9.16)
      - check-success=main (macos-12, 3.10.11)
    actions:
      merge:
        method: squash
        allow_merging_configuration_change: true
