[tool.poetry]
name = "python-cli-tool-scaffold"
version = "0.0.1"
description = "An awesome description"
authors = ["Your name <your@email.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<repo-owner>/python-cli-tool-scaffold"
repository = "https://github.com/<repo-owner>/python-cli-tool-scaffold"
include = [ "LICENSE.md" ]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
pretty-errors = "1.2.25"
vulture = "2.7"
click = "8.1.3"

[tool.poetry.dev-dependencies]
flake8 = "5.0.4"
black = "22.12.0"
bandit = "1.7.5"
pytest = "7.3.1"
pytest-cov = "4.0.0"

[tool.poetry.scripts]
python-cli-tool-scaffold = "python_cli_tool_scaffold:main"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
