[tool.poetry]
name = "python-cli-tool-scaffold"
version = "0.0.1"
description = "An awesome description"
authors = ["Your name <your@email.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<repo-owner>/python-cli-tool-scaffold"
repository = "https://github.com/<repo-owner>/python-cli-tool-scaffold"
include = [ "LICENSE.md" ]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
pretty-errors = "1.2.24"
vulture = "2.3"
click = "8.0.1"

[tool.poetry.dev-dependencies]
flake8 = "3.9.2"
black = "21.8b0"
bandit = "1.7.0"
pytest = "6.2.4"
pytest-cov = "2.12.1"

[tool.poetry.scripts]
python-cli-tool-scaffold = "python_cli_tool_scaffold:main"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
