[tool.poetry]
name = "python-cli-tool-scaffold"
version = "0.0.1"
description = ""
authors = ["Your name <your@email.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/dotanuki-labs/python-cli-tool-scaffold"
repository = "https://github.com/dotanuki-labs/python-cli-tool-scaffold"
include = [ "LICENSE.md" ]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "3.8.5"
flake8 = "3.8.3"

[tool.poetry.dev-dependencies]
pytest = "6.0.0"
pytest-cov = "2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
