[tool.poetry]
name = "python_cli_tool_scaffold"
version = "0.0.1"
description = ""
authors = ["Your name <your@email.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/<repo-owner>/python_cli_tool_scaffold"
repository = "https://github.com/<repo-owner>/python_cli_tool_scaffold"
include = [ "LICENSE.md" ]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.8"
pretty-errors = "^1.2.23"
vulture = "^2.3"

[tool.poetry.dev-dependencies]
flake8 = "3.9.2"
black = "^21.7b0"
bandit = "^1.7.0"
pytest = "6.2.4"
pytest-cov = "2.12.1"

[tool.black]
line-length = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
